import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const oscine = localFont({
  src: [
    {
      path: '../../public/fonts/Oscine_Trial_Lt.ttf',
      weight: '300'
    },
    {
      path: '../../public/fonts/Oscine_Trial_Rg.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/Oscine_Trial_Bd.ttf',
      weight: '700'
    }
  ],
  variable: '--font-oscine'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${oscine.variable} antialiased font-Oscine bg-slate-200`}
      >
        {children}
      </body>
    </html>
  );
}
